### ISSUE TITLE
PHP warnings displayed at http://coordino.com/ ?

### ISSUE THREAD

**Issue by hartwork** [Datawalke/Coordino#108]
At the top of http://coordino.com/ I see this:

```
Strict Standards: Redefining already defined constructor for class Object in /home/coordino/public_html/cake/libs/object.php on line 63

Strict Standards: Non-static method Configure::getInstance() should not be called statically in /home/coordino/public_html/cake/bootstrap.php on line 43
```

Does not look intended to me :)

**Comment by vargalas** [comment]
Indeed. Also the signup is down. :( 
Unfortunately, because this project looks fine.

**Comment by Datawalke** [comment]
Thanks for reporting this. I'll try to get the website updated at some point -- I may just have it redirect to this project or setup a demo site on the coordino.com domain.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
